# Server configuration
server.port=8080
server.servlet.context-path=/
server.error.include-message=always
server.error.include-binding-errors=always

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tttn_final_dot1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
app.file.upload-dir=./uploads

# Logging configuration
logging.level.root=INFO
logging.level.com.stu.attendance=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


# QR code configuration
app.qrcode.validity-minutes=5
app.qrcode.size=250

# Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Attendance policy
app.attendance.late-threshold-minutes=15

# C?u h�nh JWT
app.jwt.secret=zCyq3xUT2cq5CwPyI5Q3Pv6fVpQ5LQ9aKQFURplA3OTyZP9NjIEGl3EVB4B2xxfQ9sHj8LKX2gqgLfXrxr1FzA==
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=86400000

# Zalo Configuration
zalo.app.id=3353479530876761341
zalo.app.secret=bcdcde76e4deb3fe91288e5b66c47a19
zalo.redirect-uri=https://your-domain.com/auth/zalo/callback

# Mail server config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thuatvan1012@gmail.com
spring.mail.password=ogtr ixab qnbi pbzk
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
